services:
  api:
    build: .
    image: dashhook/api:2.3.0
    container_name: dashhook-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/app/app
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app:Z
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  worker:
    build: .
    image: dashhook/worker:2.3.0
    container_name: dashhook-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/app/app
      - REDIS_HOST=redis
    volumes:
      - .:/app:Z
    command: arq app.worker.WorkerSettings --watch /app
    depends_on:
      - redis

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: dashhook-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data_dev:

networks:
  default:
    name: tiger_network
    driver: bridge