services:
  api:
    build: .
    image: dashhook/api:2.0.0
    container_name: dashhook-api
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/app/app
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - redis

  worker:
    build: .
    image: dashhook/worker:2.0.0
    container_name: dashhook-worker
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/app/app
      - REDIS_HOST=redis
    command: arq app.worker.WorkerSettings
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: dashhook-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"

volumes:
  redis_data: